### ISSUE TITLE
Plugin not load on my server

### ISSUE THREAD

**Issue by piete2** [arboriginal/TidyingChest#10]
Hi! I'm so sorry, I'm noob in this mod and I can't find the error when I load the plugin in my server.

Te server says:
`[15:45:09] [Server thread/INFO]: [TidyingChest] Enabling TidyingChest v1.0
[15:45:09] [Server thread/ERROR]: Error occurred while enabling TidyingChest v1.0 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Server.spigot()Lorg/bukkit/Server$Spigot;
        at me.arboriginal.TidyingChest.TCPlugin.onEnable(TCPlugin.java:43) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:344) [craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:448) [craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:374) [craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.reload(CraftServer.java:787) [craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
        at org.bukkit.Bukkit.reload(Bukkit.java:576) [craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) [craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) [craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:690) [craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:676) [craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
        at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:422) [craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:387) [craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:940) [craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:789) [craftbukkit-1.15.2.jar:git-Bukkit-8160e29]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

The version is 1.15.2 in spiggot. Thanks

**Comment by arboriginal** [comment]
fais la poule, tu verras ce s'ra plus cool !
