### ISSUE TITLE
0.9 Invalid plugin.yml; 0.8 is working

### ISSUE THREAD

**Issue by axi92** [arboriginal/TidyingChest#7]
**Describe the bug**
Version 0.9 is not loading in Spigot 1.15 with the error "Invalid plugin.yml"

Full error log:
```
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Loading libraries, please wait...
[12:44:34] [Server thread/INFO]: Starting minecraft server version 1.15
[12:44:34] [Server thread/INFO]: Loading properties
[12:44:34] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-3b314f5-e2790ae (MC: 1.15) (Implementing API version 1.15-R0.1-SNAPSHOT)
[12:44:34] [Server thread/INFO]: Debug logging is disabled
[12:44:34] [Server thread/INFO]: Server Ping Player Sample Count: 12
[12:44:34] [Server thread/INFO]: Using 4 threads for Netty based IO
[12:44:34] [Server thread/INFO]: Default game type: SURVIVAL
[12:44:34] [Server thread/INFO]: Generating keypair
[12:44:35] [Server thread/INFO]: Starting Minecraft server on *:25565
[12:44:36] [Server thread/INFO]: Using epoll channel type
[12:44:36] [Server thread/ERROR]: Could not load 'plugins/TidyingChest-0.9.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:168) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:138) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:351) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:783) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.util.zip.ZipException: zip END header not found
	at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1535) ~[?:?]
	at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1436) ~[?:?]
	at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1443) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1274) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1237) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:247) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:177) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:346) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:317) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:283) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:156) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
	... 5 more
```

**To Reproduce**
Setup a fresh dir with spigot-1.15.jar and the plugin version 0.9 and start with `java -Xms2G -Xmx4G -XX:+UseConcMarkSweepGC -jar spigot-1.15.jar`

**Expected behavior**
Plugin should load.

**Environment**
Java Version:
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04, mixed mode, sharing)

 - Spigot version: 1.15
 - Plugin version: 0.9 (on 0.8 it is working)
 - Plugin configuration: no config is generated neither a folder is created.
 - Error log: https://gist.github.com/axi92/b5b89841b1ee48bcca93ed2bdb2e8fca

**Additional context**
I tried 0.8 and it is loading.
I will try it with 1.15.1 and report the result here.

---

By submitting this issue, you confirm having read, understand and accepted its guideline.
You also confirm having a functional brain activated during the writing of this issue.

**Comment by arboriginal** [comment]
Thanks for the report, I'll check ASAP but with Christmas period, I'm running out of time...

I'm also waiting you test with 1.15.1 as I'm using it with it and 1.15 is not maintained by Spigot (replaced by 1.15.1): So if the problem is only in it, the way to solve is to upgrade to 1.1.5.1.

Also, reading your log first line, UseConcMarkSweepGC option is deprecated and so, if this is the problem, I won't make something for it, but simply tell you not to use it (deprecated now, will disappear in newer Java version).

Without having make tests for now:
The error is saying "plugin.yml" is invalid... But between 0.8 and 0.9 I've simply change "spigo" by "spigot" in a Maven variable, so it's transparent for the resulting plugin.yml in the jar... Strange.

**Comment by arboriginal** [comment]
Quick tests:
* tested with a fresh 1.15, Java 8, with given args => Load without issues
* tested with a fresh 1.15, Java 8, without special args => Load without issues
* tested with a fresh 1.15, Java 12, without special args => Load without issues
* tested with a fresh 1.15, Java 12, with given args => Load without issues

BTW: "1.15 is not your server version, type "version" command to know the correct version number (and if is told you your version is outdated, update it).

**Comment by arboriginal** [comment]
I forgot to ask... Did you use my release jar or did you compile the plugin by yourself?

**Comment by arboriginal** [comment]
I've just installed Java 11 and so, I complete my tests:
* tested with a fresh 1.15, Java 11, without special args => Load without issues
* tested with a fresh 1.15, Java 11, with given args => Load without issues

I realize your log said "Caused by: java.util.zip.ZipException: zip END header not found"... So maybe the jar file you used is corrupted. Try to re-download it.

**Comment by axi92** [comment]
md5sum TidyingChest-0.9.jar 
ca99a16ce70dd37c845f7998f01d975e  TidyingChest-0.9.jar

I downloaded it again from github releases:
md5sum TidyingChest-0.9.jar 
c756bb37d2bbec4e90d2e6827dac398a  TidyingChest-0.9.jar

It seems like the file was corrupted. I would never come to this idea!

Ty for your help and sry for the late response I was at the christmas market =)
